language: node_js
node_js:
  - "6.10.3"
after_success:
  - npm install
  - npm test
  after_success:
  - npm install -g codeclimate-test-reporter
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codeclimate-test-reporter < lcov.info